<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Scheduled task that embeds knowledge-base chunks still lacking a vector.
 *
 * @package    block_openaiagent
 * @copyright  2025 RSMAX Consulting SL <julio@rsmax.es>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace block_openaiagent\task;

use block_openaiagent\local\tutordocs;

/**
 * Retries embedding generation for any course whose chunks are not yet embedded.
 *
 * Chunks are created immediately when a teacher saves the course knowledge base,
 * but their embeddings are generated by an API call that can fail transiently.
 * This sweep re-runs on cron so those courses become searchable semantically
 * without the teacher having to re-save the configuration.
 */
class embed_chunks_task extends \core\task\scheduled_task {
    /**
     * The task name shown in the scheduled tasks admin report.
     *
     * @return string
     */
    public function get_name(): string {
        return get_string('task_embed_chunks', 'block_openaiagent');
    }

    /**
     * Embed pending chunks across all courses.
     */
    public function execute(): void {
        tutordocs::embed_all_pending();
    }
}
